---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/hagcapmy/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
	- /bin/cp credits.html $DEPLOYPATH
	- /bin/cp -R images $DEPLOYPATH
	- /bin/cp -R bokeh $DEPLOYPATH
	- /bin/cp -R js $DEPLOYPATH
	- /bin/cp -R sound $DEPLOYPATH